uploads = []
generated = []

[[outputs]]
id = "2WmhgKCKEt4yIncAVB7NC"
uri = "file://dist.zip"
type = "unspecified"
title = "Facebook Login Clone — dist.zip"

[[outputs]]
id = "ar8_gSlYabmD1ezQ0QYev"
uri = "file://hostking_upload.zip"
type = "unspecified"
title = "HostKing Upload Package"

[[outputs]]
id = "AT7h-clPw3jmJ_3DXij6m"
uri = "file://index_fix.zip"
type = "unspecified"
title = "index.html fix — extract and upload to public_html"
