uploads = []
generated = []

[[outputs]]
id = "2WmhgKCKEt4yIncAVB7NC"
uri = "file://dist.zip"
type = "unspecified"
title = "Facebook Login Clone — dist.zip"

[[outputs]]
id = "ar8_gSlYabmD1ezQ0QYev"
uri = "file://hostking_upload.zip"
type = "unspecified"
title = "Updated site files — upload & extract to public_html"

[[outputs]]
id = "AT7h-clPw3jmJ_3DXij6m"
uri = "file://index_fix.zip"
type = "unspecified"
title = "index.html fix — extract and upload to public_html"

[[outputs]]
id = "3UDaUlSZugbuotsmBhBoC"
uri = "file://index.txt"
type = "text"
title = "index.html — download and rename to index.html"
